import type { DashboardLink } from '@/components/dashboard/DashboardShell'

export const dashboardLinks: Record<string, DashboardLink[]> = {
  admin: [
    ['Overview', '/admin'],
    ['Live Fleet', '/admin/fleet'],
    ['Routes', '/admin/routes'],
    ['Schools', '/admin/schools'],
    ['Crew', '/admin/crew'],
    ['Vetting', '/admin/vetting'],
    ['Vehicles', '/admin/vehicles'],
    ['Alerts', '/admin/alerts'],
    ['Incidents', '/admin/incidents'],
    ['Parents', '/admin/parents'],
    ['Notifications', '/admin/notifications'],
    ['Analytics', '/admin/analytics'],
    ['Billing', '/admin/billing'],
    ['Partners', '/admin/partners'],
    ['Onboarding', '/admin/onboarding'],
    ['Settings', '/admin/settings'],
  ].map(([label, href]) => ({ label, href })),
  school: [
    ['Overview', '/dashboard/school'],
    ['Live Fleet', '/dashboard/school/fleet'],
    ['Students', '/dashboard/school/students'],
    ['Routes', '/dashboard/school/routes'],
    ['Crew Profiles', '/dashboard/school/crew'],
    ['Safeguarding', '/dashboard/school/safeguarding'],
    ['Parent Comms', '/dashboard/school/comms'],
    ['Attendance', '/dashboard/school/attendance'],
    ['Billing', '/dashboard/school/billing'],
    ['Reports', '/dashboard/school/reports'],
    ['White Label', '/dashboard/school/whitelabel'],
    ['Settings', '/dashboard/school/settings'],
  ].map(([label, href]) => ({ label, href })),
  parent: [
    ['My Children', '/dashboard/parent'],
    ['Live Tracking', '/dashboard/parent/tracking'],
    ['Journey History', '/dashboard/parent/history'],
    ['Guardians', '/dashboard/parent/guardians'],
    ['Profile', '/dashboard/parent/profile'],
    ['Messages', '/dashboard/parent/messages'],
  ].map(([label, href]) => ({ label, href })),
  driver: [
    ['Today', '/dashboard/driver'],
    ['Route', '/dashboard/driver/route'],
    ['Manifest', '/dashboard/driver/manifest'],
    ['Alerts', '/dashboard/driver/alerts'],
    ['Profile', '/dashboard/driver/profile'],
  ].map(([label, href]) => ({ label, href })),
  codriver: [
    ['Today', '/dashboard/codriver'],
    ['Manifest', '/dashboard/codriver/manifest'],
    ['Children', '/dashboard/codriver/children'],
    ['Alerts', '/dashboard/codriver/alerts'],
    ['Profile', '/dashboard/codriver/profile'],
  ].map(([label, href]) => ({ label, href })),
  nurse: [
    ['Today', '/dashboard/nurse'],
    ['Children', '/dashboard/nurse/children'],
    ['Welfare Notes', '/dashboard/nurse/welfare'],
    ['First Aid', '/dashboard/nurse/firstaid'],
    ['Profile', '/dashboard/nurse/profile'],
  ].map(([label, href]) => ({ label, href })),
  partner: [
    ['Overview', '/dashboard/partner'],
    ['My Vehicles', '/dashboard/partner/vehicles'],
    ['Live Tracking', '/dashboard/partner/tracking'],
    ['Earnings', '/dashboard/partner/earnings'],
    ['Inspections', '/dashboard/partner/inspections'],
    ['Documents', '/dashboard/partner/documents'],
    ['Profile', '/dashboard/partner/profile'],
  ].map(([label, href]) => ({ label, href })),
}
